apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-demo-chart.fullname" . }}
  labels:
{{ include "helm-demo-chart.labels" . | indent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.containers.secrets }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- range $key, $value := .Values.containers.extraSecrets }}
  {{ $key }}: {{ $value | quote }}
{{- end }}